### ISSUE TITLE
Removing additional dependency from Bookstore service API.

### ISSUE THREAD

**Issue by dhruv007patel** [scp756-221/term-project-data-miners#17]
As part of this issue, we need to make the new service run independently of the provided shell scripts. 
- Need to create new DockerFile and Makefile to support. 
- Once, developed need to test all edge cases for the new service.

**Comment by RahilBalar98** [comment]
@dhruv007patel @Himalya lets pass the data base end points instead of local dictionary to store the data

**Comment by dhruv007patel** [comment]
Hi @RahilBalar98, pushed needed changes into the feature. Kindly review!

**Comment by Himalya** [comment]
Hi, @RahilBalar98 I have also pushed the required changes to my feature branch. Please review and merge!

**Comment by RahilBalar98** [comment]
Reviewed, will merge it!
