### ISSUE TITLE
Deploying the services in the Kubernetes.

### ISSUE THREAD

**Issue by Kishan-Thumar** [scp756-221/term-project-data-miners#20]
To deploy the DB, S1, S2, Bookstore services on the Kubernetes, in order to achieve that I and @dhruv007patel will be looking into the following sub-task.

- [x] Setting up the minikube cluster & cloud cluster
- [x] Installing Service mesh 
- [x] Tunneling into your cluster in the minikube & cloud
- [x] Deploying the services.

**Comment by dhruv007patel** [comment]
Finished setting up a minikube cluster in the local. Now working towards deploying this new service and testing in the local cluster.
