### ISSUE TITLE
Add bookstore service in Grafana and Gatling

### ISSUE THREAD

**Issue by Himalya** [scp756-221/term-project-data-miners#21]
- [x] @dhruv007patel and @Himalya Configuring bookstore service in Gatling 
- [x] @Kishan-Thumar  will be configuring DB requests to the Gatling (for bookstore service)
- [x] @RahilBalar98 will be provisioning Gatling and Grafana for sample load testing

**Comment by dhruv007patel** [comment]
Hi, I achieved the following task, and elaborated details of the task can be found in the following issue. Refer here [#39, #5 and #25]

Thanks!
