### ISSUE TITLE
Creating shell script for gatling (load testing)

### ISSUE THREAD

**Issue by RahilBalar98** [scp756-221/term-project-data-miners#25]

**Comment by Kishan-Thumar** [comment]
@RahilBalar98 the template provided in the guide is for a different number of users. We need to make sure that the number of users and the service can be passed during rum time so we can avoid multiple files.

**Comment by RahilBalar98** [comment]
@Kishan-Thumar committed [the changes ](9550a650a9620886b95a7e015537722dc1fbcf7c) please verify it.
